/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myapplication

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val result = CommandImpl(
            listOf(FizzRule(),BuzzRule(),EmptyRule())
        ).execute(10)

        assertEquals(result, "")
    }
}
