@startuml
actor User
participant "Android or iOS" as App
participant "サーバA" as ServerA
participant "GCP" as GCP

User -> App: PCM形式の音声を送信
App -> App: PCM形式の音声をバイト配列に変換
App -> ServerA: Base64（data）に変換後送信
ServerA -> ServerA: Base64形式の音声をFlac形式に変換
ServerA -> GCP: 変換した音声データを送信
GCP -> ServerA: 変換結果を受信
ServerA -> App: 結果をBase64（data）に変換後送信
App -> User: 結果を受信

note left
API仕様
{
  "data": "SGVsbG8gV29ybGQh",
  "type": "audio/wav"
}

レスポンス
{
  "data": "String結果",
  "error":"何らかのエラーが起きた際に設定される文字列"
}
end note
@enduml
